### ISSUE TITLE
Grabs all CPU

### ISSUE THREAD

**Issue by jult** [MoonchildProductions/FossaMail#16] opened 2016-03-09 08:39 UTC
On several different Win7 x64 instances it quite often freezes/stalls all CPU/activity. My guess is it does this while reading large mailfolders or something. It's very annoying. I just can't do anything, not even type. It keeps the keyboard input though, and then spills what you typed all at once, when it releases its lock again, it seems.

Have switched over to other mail-clients for that reason, only to find that fossamail is the only one with a workable interface. Except for that strange lag it imposes on my PC's/laptop.

**Comment by wolfbeast** [comment] 2016-03-09 10:19
I ran into something very similar very recently myself after purchasing and installing Bitdefender AV (2016). I ended up discarding the AV for something else which solved my problems; maybe that's an area to look in.

**Comment by jult** [comment] 2016-03-09 10:24
Naa, sorry, it's fossamail. Also visible through running processes. Uses up all CPU then releases it. When I quit the program, everything is fine and dandy. I don't run any AV. I do use firefox x64 v45 together with fossamail though, which seem to interact in buggy ways. Sometimes one or the other crashes and then takes the other down with it.

**Comment by wolfbeast** [comment] 2016-03-09 11:25
That should never happen, since both applications are completely separate, so something else is going on here. Jumping to conclusions and blaming FossaMail based on a hunch because you only see a symptom in the mail client isn't exactly a good bug report that we can do anything with. We need more information and a way to reproduce it.

For the record, I have Moz FF installed as well, on the same OS, and never see any sort of interaction issues.

See if you can get a Hang report with WhatIsHang?

**Comment by ericchill** [comment] 2016-04-28 22:22
I recently observed this on x86_64 Ubuntu as well. Top showed 107% CPU. The problem seems to be gone in FossaMail 25.2.1.

**Comment by wolfbeast** [comment] 2016-04-28 23:36
I'll be closing this for now. No further info by original reporter submitted and apparently similar behavior has been solved in FossaMail-current.

**Closed by wolfbeast** 2016-04-28 23:36 UTC
Labels: more info needed
