### ISSUE TITLE
Fossamail PPA for Debian Based Linux Systems

### ISSUE THREAD

**Issue by MartinX3** [MoonchildProductions/FossaMail#22] opened 2017-01-06 14:57 UTC
Are there any plans to serve FossaMail in the same PPA where i get PaleMoon?
The PPA from @stevenpusser

**Comment by wolfbeast** [comment] 2017-03-24 12:58
Duplicate of #31

**Closed by wolfbeast** 2017-03-24 12:58 UTC
Labels: duplicate, question

**Comment by stevenpusser** [comment] 2017-04-05 03:37
Hmmm...it's not a PPA, but I'll see if I can build it.

**Comment by MartinX3** [comment] 2017-04-05 19:41
That sounds nice, if you need any help, ask me.
I am able to build it on my Linux Machine (Ubuntu 16.04).
I work on a FossaMail PPA, but my final exams (now, I am fishish with them) did slow me down.
